### ISSUE TITLE
Difficulty picking up items

### ISSUE THREAD

**Issue by ChromesDuzez** [PlatFormPlayZ/CIS-350-Project-1#5]
Picking up trash off the ground is not the easiest thing to do. Kinda have to be almost directly on top of the item without actually standing on it or else you are too high up.

Question 1: Would switching from a ray to a cone, like Professor Schaffer suggested fix the issue? Or would it be good to do it either way?

Question 2: Would implementing a crouching feature help this issue?

Question 3: If we stick with the ray, would there be a way to extend the "reach" of the player help mitigate this issue?

**Comment by MYTEE-MITE** [comment]
Making it a skinny cone and extending the reach would be the easiest way to go for sure

**Comment by ChromesDuzez** [comment]
Sounds good. Do we want to consider the movement options such as jump and crouch? just for general purposes but not to necessarily help with this issue. If so I can create another ticket for tracking such changes.

**Comment by ChromesDuzez** [comment]
Jump Movement Idea Resolved in commit [33f5752](https://github.com/PlatFormPlayZ/CIS-350-Project-1/commit/33f57523b57b7664355f84c9d0bf652190e23c36) by @lwjohnson-18.

**Comment by ChromesDuzez** [comment]
- [x] Increase Range for pickup

**Comment by ChromesDuzez** [comment]
Pickup Range fixed in commit [f4fa1f5](https://github.com/PlatFormPlayZ/CIS-350-Project-1/commit/f4fa1f534af1b0456fe2e1e01db1b94c557f216d).
